Add --additional-names flag

diff --git a/run-integration-test b/run-integration-test
--- a/run-integration-test
+++ b/run-integration-test
@@ -1,6 +1,8 @@
 #!/usr/bin/env sh
 
-# nix-build
+FAILED=0
+
+nix-build
 
 generate_ca_test() {
     echo "Test CA generation"
@@ -28,6 +30,7 @@ generate_server_cert_test() {
         --ca-path tmp/ca \
         --additional-address 1.2.3.4 \
         --additional-address 5.6.7.8 \
+        --additional-name test.name \
         tmp/server_cert
 }
 
@@ -38,6 +41,7 @@ run_testcase(){
         echo "...  passed."
     else
         echo "... failed."
+        FAILED=$(($FAILED + 1))
     fi
 }
 
@@ -46,3 +50,11 @@ TESTCASES="generate_ca_test generate_client_cert_test generate_server_cert_test"
 for testcase in $TESTCASES; do
     run_testcase "${testcase}"
 done
+
+if [ 0 -ne "${FAILED}" ]; then
+    echo "${FAILED} TESTS FAILED"
+    exit 1
+else
+    echo "success"
+    exit 0
+fi
